### ISSUE TITLE
I'm basically just dumping the glitches that kinda annoyed me in this GAPPS Package

### ISSUE THREAD

**Issue by UltraCenterHQ** [BiTGApps/BiTGApps-Release#1]
> 2nd glitch: For some reason, when you flash BITGapps 4.2, it prevents you from deleting system app files in the TWRP File Manager. You need to reboot to fix it.

You need to mount system partition.

**Comment by TheHitMan7** [comment]
> 1st glitch: The Webview and Chrome Addons makes Lineage 20 go on a bootloop. It doesn't even get fixed if you removed the apps in the TWRP File Manager

I can provide these addons with fixes, if you have time to test. This can be done faster on telegram support chat [@BiTGAppsChat](https://t.me/BiTGAppsChat).

**Comment by TheHitMan7** [comment]
> I know. You can't even see the app files without mounting the system

But system should be in read-write state and not read-only. In read-only, you can see the files but cannot delete them.

**Comment by TheHitMan7** [comment]
> > 1st glitch: The Webview and Chrome Addons makes Lineage 20 go on a bootloop. It doesn't even get fixed if you removed the apps in the TWRP File Manager
> 
> I can provide these addons with fixes, if you have time to test. This can be done faster on telegram support chat [@BiTGAppsChat](https://t.me/BiTGAppsChat).
> 
> _EDIT: I think this is caused by WebView Addon and not chrome one's._

@UltraCenterHQ What about this ?

**Comment by UltraCenterHQ** [comment]
> > 1st glitch: The Webview and Chrome Addons makes Lineage 20 go on a bootloop. It doesn't even get fixed if you removed the apps in the TWRP File Manager
> 
> I can provide these addons with fixes, if you have time to test. This can be done faster on telegram support chat [@BiTGAppsChat](https://t.me/BiTGAppsChat).
> 
> _EDIT: I think this is caused by WebView Addon and not chrome one's._

**Comment by TheHitMan7** [comment]
I will fixed with next released.

**Comment by TheHitMan7** [comment]
> Hmm, I tried it separately before and I tried it again. Weird how it only affects the addons that have the Sandbox file in it.

In what manner, like did you first flash chrome addon and booted into system or your first flash webview addon. I don't think so it has anything to do with Sandbox. We do remove AOSP webview with webview addon installation, maybe that is causing this issue.

Try booting first with BiTGApps then flash chrome addon and boot into system then try chrome addon. It is easier to troubleshoot with this.

> Also, I don't really like telegram, you could just send me a download link with a fixed addon

I cannot fix anything until you do proper testing and we both available at same time. So telegram is best for that purpose.

**Comment by UltraCenterHQ** [comment]
> In what manner, like did you first flash chrome addon and booted into system or your first flash webview addon. I don't think so it has anything to do with Sandbox. We do remove AOSP webview with webview addon installation, maybe that is causing this issue.

I installed it separately. Tried ROM + Core + Chrome. And then I formatted it and tried ROM + Core + Webview.

And by experience, Android boots up pretty well even with most apps removed. Lacking WebView just caused google sign-in to crash and some apps to just show a black screen

**Comment by TheHitMan7** [comment]
> I installed it separately. Tried ROM + Core + Chrome. And then I formatted it and tried ROM + Core + Webview.

Then bootloop happen where ?

**Comment by UltraCenterHQ** [comment]
> Then bootloop happen where ?

They both bootlooped either way

**Comment by TheHitMan7** [comment]
> > Then bootloop happen where ?
> 
> They both bootlooped either way when I rebooted to system. I'm going to try the method you said earlier

Means booting is fine with core and not with these two ?

**Comment by TheHitMan7** [comment]
Also bring recovery.log which is stored in /tmp, when in recovery after BiTGApps core installation. You can either copy paste it using recovery file manager or use:

`adb pull /tmp`

**Comment by UltraCenterHQ** [comment]
here
ROM + OMNI + CHROME [recovery.log](https://github.com/user-attachments/files/17852481/recovery.log)

ROM + OMNI + WEBVIEW [recovery.log](https://github.com/user-attachments/files/17852485/recovery.log)

**Comment by TheHitMan7** [comment]
> here ROM + OMNI + CHROME [recovery.log](https://github.com/user-attachments/files/17852481/recovery.log)
> 
> ROM + OMNI + WEBVIEW [recovery.log](https://github.com/user-attachments/files/17852485/recovery.log)

Logs does not even contain installation logs.

**Comment by TheHitMan7** [comment]
> Steps here:
> 
> 1. Flash BiTGApps Core and boot into system
> 2. If this goes well then try flashing chrome addon and boot into system
> 3. If both steps let you boot into system try flashing webview addon and try booting

Follow this.

**Comment by TheHitMan7** [comment]
> Also bring recovery.log which is stored in /tmp, when in recovery after BiTGApps core installation. You can either copy paste it using recovery file manager or run below command in terminal.
> 
> `adb pull /tmp`

Read properly what is written here. You are supposed to copy logs when installation is done, if you reboot and copy after that logs will have nothing.

**Comment by TheHitMan7** [comment]
@UltraCenterHQ Just do one thing, flash **BiTGApps Core Version**, and no addons then pull recovery.log **before** rebooting into recovery or system.

**Comment by TheHitMan7** [comment]
> Here (Sorry for the late replies) Rom + Core: [recovery.log](https://github.com/user-attachments/files/17870682/recovery.log)

Did you able to boot into system with rom + core ?

**Comment by UltraCenterHQ** [comment]
yes

**Comment by TheHitMan7** [comment]
> yes

Wait, lets make this clear.

From three options, let me with which you able to boot into system like 1. Yes, etc.

1. Rom + Core: Yes/No
2. Rom + Core + Chrome: Yes/No
3. Rom + Core + Webview: Yes/No

**Comment by UltraCenterHQ** [comment]
Chrome and WebView causes a bootloop, that's why I'm kinda here

**Comment by TheHitMan7** [comment]
> Both Chrome addon and WebView addon causes a bootloop, that's why I'm kinda here

Send ROM link.

**Comment by UltraCenterHQ** [comment]
Here https://xdaforums.com/t/rom-unofficial-ms013g-13-lineageos-20-0-alpha.4637768/
I'm planning to test out the previous Lineage 19 port if the addons causes a bootloop too. because for some reason, even litegapps gets stuck in a bootloop. It's a really specific issue

**Comment by TheHitMan7** [comment]
@UltraCenterHQ  I think i should leave this for good, due to couple of reasons:

1. You're not providing any relevant information which could help fix this issue
2. Your device is super old like from 2014
3. So much delay in response from your side, whatever motivation i have left to fix, also gone away due to this
4. Fixing things need time and some work, which i didn't see here from start.
5. No proper installation logs, no adb logcat to dig more into this issue.

You can continue with whatever works for you.

Thanks!
