### ISSUE TITLE
Updater process ended with ERROR: 1

### ISSUE THREAD

**Issue by rebelcode-xr** [BiTGApps/BiTGApps-Release#1]
Cannot install [BiTGApps-arm64-11.0.0-v1.1_signed.zip](https://github.com/BiTGApps/BiTGApps-Release/releases/download/v1.1/BiTGApps-arm64-11.0.0-v1.1_signed.zip):

![screen](https://user-images.githubusercontent.com/63522951/188209603-dd02b878-70ec-48e7-94a2-2dfd2b334083.jpg)

I tried twice without success...then I tried the previous version [BiTGApps-arm64-11.0.0-v1.0_signed.zip](https://github.com/BiTGApps/BiTGApps-Release/releases/download/v1.0/BiTGApps-arm64-11.0.0-v1.0_signed.zip) and it worked...🤔

**Comment by TheHitMan7** [comment]
This is a know bug in v1.1 and we have already fixed it, changes will reflect with next stable.

**Comment by rebelcode-xr** [comment]
ah ok, maybe would be better to write it next to the download! ;) thank you!
